title: This is supposed to be the Modernist theme
description: Tactile is a theme for GitHub Pages.
show_downloads: false
<!--- google_analytics: --->
theme: jekyll-theme-tactile 
<!--- remote_theme: pages-themes/tactile@v0.2.0--->
<!--- plugins:--->
<!--- - jekyll-remote-theme--->
