title: This is supposed to be the Modernist theme
description: Tactile is a theme for GitHub Pages.
show_downloads: false
google_analytics:
<!--- theme: jekyll-theme-tactile --->
plugins:
- jekyll-remote-theme
remote_theme: pages-themes/modernist@v0.2.0
